---
- hosts: demo
  gather_facts: false
  become: true

  tasks:
  - name: Install python3-pip module
    apt:
      name: "{{ item.package_name }}"
      state: latest
    with_items:
    - { package_name: python3-pip}

  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
    - { name: docker, version: 2.0.0 }

  - name: Create a data container
    docker_container:
      name: web
      image: nginxdemos/hello
      ports:
      - "8000:80"

- hosts: web
  gather_facts: true
  become: true

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
  
  - name: Upload nginx config
    copy:
      src: ./nginx/lb.conf
      dest: /etc/nginx/conf.d/lb.conf

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
  
  - name: get public IP
    shell:
      cmd: curl -s https://api.ipify.org/ 
    register: public_ip
  - name: output
    debug: msg="{{ public_ip.stdout }}"

  # - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  - name: Create a test.example.net A record to point to web
    community.general.cloudflare_dns:
      zone: dopevs.cloud
      record: demo
      type: A
      value: "{{ public_ip.stdout }}"
      account_email: waiyanwinhtain224@gmail.com
      account_api_key: "{{ API_TOKEN }}"
    register: record

  - name: output
    debug: msg="{{ record }}"